apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    tekton.dev/signature: MEYCIQDoZMhT7RCfJ/103JOUoaxz7xULTNrDnDX4rZvzhbvwrgIhAKKFd9ZUGeff9eLG3LY4twHRGZ9eLrXPk/nMUx8hLpBl
  creationTimestamp: null
  name: example-pipeline
  namespace: trusted-resources
spec:
  tasks:
  - name: example-task
    taskRef:
      params:
      - name: url
        value: https://github.com/Yongxuanzhang/sample-tekton-task
      - name: revision
        value: main
      - name: pathInRepo
        value: signed-task.yaml
      resolver: git
