apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    tekton.dev/signature: MEQCIBl4g1e51xXRGsKv65ufEMyxjqHWsqqsQmCVkKQeKGmuAiAygFyMaEwl8cXr3g2bnUjWG6UilQx6U5mlryQXJX3paQ==
  creationTimestamp: null
  name: example-pipeline
  namespace: trusted-resources
spec:
  tasks:
  - name: example-task
    taskRef:
      params:
      - name: url
        value: https://github.com/Yongxuanzhang/sample-tekton-task
      - name: revision
        value: main
      - name: pathInRepo
        value: signed-task.yaml
      resolver: git
