apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    tekton.dev/signature: MEYCIQDUE1jNAE/RL+kglUpRHYtDzZL3cOAQCWlKYredC+OZmwIhAK8gw94/w31cz2HIqXh6v+sxLFWhWbb1ANajbvIT+dyn
  creationTimestamp: null
  name: example-pipeline
  namespace: trusted-resources
spec:
  tasks:
  - name: example-task
    taskRef:
      params:
      - name: url
        value: https://github.com/Yongxuanzhang/sample-tekton-task
      - name: revision
        value: main
      - name: pathInRepo
        value: signed-task-cosign.yaml
      resolver: git
