apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    tekton.dev/signature: MEUCIQDiAhiVRT2Ba8/zACMInnPxZN1BPSPSyMBcoXt+xRvMAgIgU6CY0tq6TIT1PY6K2T0eTURJ/fNYfbTDKobdE/i5xQ8=
  creationTimestamp: null
  name: example-pipeline
  namespace: trusted-resources
spec:
  tasks:
  - name: example-task
    taskRef:
      params:
      - name: url
        value: https://github.com/Yongxuanzhang/sample-tekton-task
      - name: revision
        value: main
      - name: pathInRepo
        value: signed-task.yaml
      resolver: git
