apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    tekton.dev/signature: MEQCIHn1F8x1yAC6+5g3GKwjqxBMHH+/NlZmbYgJDcCH60lyAiB/XEoUfRCESrwE0AUIhd0feraE1/FP4kuXVbLZW89m8A==
  creationTimestamp: null
  name: example-pipeline
  namespace: trusted-resources
spec:
  tasks:
  - name: example-task
    taskRef:
      params:
      - name: url
        value: https://github.com/Yongxuanzhang/sample-tekton-task
      - name: revision
        value: main
      - name: pathInRepo
        value: signed-task.yaml
      resolver: git
